from ubuntu:mantic

run apt update && apt install -y ca-certificates golang
run go install github.com/femnad/fup@latest
entrypoint ["/root/go/bin/fup", "-f", "https://raw.githubusercontent.com/femnad/fup/ci-test/contrib/test.yml", "-b"]
