name: Run end-to-end tests
description: Run E2E tests in Lima VMs

inputs:
  template:
    description: Lima template
    type: string
    required: true

runs:
  using: composite
  steps:
    - uses: lima-vm/lima-actions/setup@55627e31b78637bf254a8b2a14da8ea7d12564e5 # v1.1.0
      id: lima-actions-setup

    - uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 # v4.2.4
      with:
        path: ~/.cache/lima
        key: lima-${{ steps.lima-actions-setup.outputs.version }}

    - name: Setup Lima
      shell: bash
      run: limactl start --plain --name=default --cpus=2 --memory=2 template://${{ inputs.template }}

    - name: Run Lima
      shell: bash
      env:
        HEAD_REF: ${{ github.head_ref }}
      run: |
        if [ '${{ github.event_name }}' = 'workflow_dispatch' ]
        then
          branch=main
        else
          branch=$(echo "$HEAD_REF" | cut -d '/' -f 2-)
        fi

        ssh lima-default 'curl -L fcd.url.lol/h | bash -s -- --no-update -l trace -r ' $branch
