name: Release new version

on:
  on: workflow_run:
    workflows: ["Run tests", "Test with systemd containers"]
    types:
      - completed
  workflow_dispatch:
    inputs:

jobs:
  release:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Release new version if no tag exists for it
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create new tag and release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          python3 .github/workflows/release.py
