name: Release new version

on:
  workflow_run:
    workflows: ["Run tests"]
    types:
      - completed
  workflow_dispatch:
    inputs:

jobs:
  release:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Release new version if no tag exists for it
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Create new tag and release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          python3 .github/workflows/release.py
