name: Run tests

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:

jobs:
  test:
    name: Run unit and integration tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Run Go tests
        run: go test ./... -tags=unit

      - name: Run integration tests
        run: |
          go install
          go test ./... -tags=integration

  container-test:
    name: Run provisioning in a container
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image: [ubuntu]
    container:
      image: femnad/fup:${{ matrix.image }}-ci

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup container
        run: |
          # https://github.com/golang/go/issues/53532
          go install -buildvcs=false
          cd cmd
          go build -buildvcs=false -o fup-verify
          cp fup-verify ~/go/bin

      - name: Provision
        run: |
          ~/go/bin/fup apply -f tests/config/test.yml -l 0 -n -b

      - name: Verify
        run: |
          ~/go/bin/fup-verify -c tests/config/test.yml -f tests/config/verify-test.yml

  container-remote-config-test:
    name: Run provisioning in a container via a remote config
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image: [ubuntu]
    container:
      image: femnad/fup:${{ matrix.image }}-ci

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup container
        run: |
          # https://github.com/golang/go/issues/53532
          go install -buildvcs=false
          cd cmd
          go build -buildvcs=false -o fup-verify
          cp fup-verify ~/go/bin

      - name: Get branch
        id: get-branch
        run: |
          event="${{ github.event_name }}"
          head_ref="${{ github.head_ref }}"
          ref_name="${{ github.ref_name }}"

          if [ "$event" = 'pull_request' ]
          then
            branch="$head_ref"
          else
            branch="$ref_name"
          fi

          echo "branch=${branch}" >> "$GITHUB_OUTPUT"

      - name: Provision
        run: |
          ~/go/bin/fup apply -f https://raw.githubusercontent.com/femnad/fup/${{ steps.get-branch.outputs.branch }}/tests/config/test-remote.yml -l 0 -n -b

      - name: Verify
        run: |
          ~/go/bin/fup-verify -c https://raw.githubusercontent.com/femnad/fup/${{ steps.get-branch.outputs.branch }}/tests/config/test-remote.yml -f tests/config/verify-test-remote.yml
