on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Go tests
        run: go test ./...

      - name: Run integration tests
        run: |
          go install
          python3 tests/test_archives.py
