on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Go tests
        run: go test ./...

      - name: Run integration tests
        run: |
          go install
          python3 tests/test_archives.py

  container-test:
    name: Run provisioning in a container
    runs-on: ubuntu-latest
    container:
      image: ubuntu:mantic
    steps:
      - uses: actions/checkout@v4

      - name: Setup container
        run: |
          apt update
          apt install -y ca-certificates golang
          go install

      - name: Provision
        run: |
          ~/go/bin/fup -f contrib/test.yml -b
